// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneAI.Data;

#nullable disable

namespace OneAI.AppMigrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221124638_AddAIAccountQuota")]
    partial class AddAIAccountQuota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("OneAI.Entities.AIAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRateLimited")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RateLimitResetTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("IsRateLimited");

                    b.HasIndex("Provider");

                    b.ToTable("AIAccounts");
                });

            modelBuilder.Entity("OneAI.Entities.AIAccountQuota", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditsBalance")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreditsUnlimited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCredits")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryOverSecondaryLimitPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryResetAfterSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrimaryResetAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryUsedPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryWindowMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondaryResetAfterSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SecondaryResetAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondaryUsedPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondaryWindowMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("LastUpdatedAt");

                    b.ToTable("AIAccountQuotas");
                });

            modelBuilder.Entity("OneAI.Entities.AIRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRateLimited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStreaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageSummary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Originator")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotaInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RateLimitResetSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestEndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestParams")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SessionStickinessUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeToFirstByteMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("IsSuccess");

                    b.HasIndex("Model");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("RequestStartTime");

                    b.HasIndex("AccountId", "RequestStartTime");

                    b.HasIndex("Model", "RequestStartTime");

                    b.ToTable("AIRequestLogs");
                });

            modelBuilder.Entity("OneAI.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("OneAI.Entities.AIAccountQuota", b =>
                {
                    b.HasOne("OneAI.Entities.AIAccount", "Account")
                        .WithOne()
                        .HasForeignKey("OneAI.Entities.AIAccountQuota", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OneAI.Entities.AIRequestLog", b =>
                {
                    b.HasOne("OneAI.Entities.AIAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
